### ISSUE TITLE
Show instances of workflows for more than last 30 days

### ISSUE THREAD

**Issue by hatfield41** [pnp/pnpassessment#11]
It's very common for workflows to be a integral part of business operations but not run within 30 days. It would be more helpful if we could go back and see how many instances ran in a calendar year.

**Comment by jansenbe** [comment]
@hatfield41: thanks for using the assessment tool and providing the feedback. The assessment tool is using public APIs and currently those APIs are not returning data beyond the mentioned 30 days. We're investigating if workflow API changes can be made to support the actual "last used" date as that would capture workflows that run less frequent.

**Comment by jansenbe** [comment]
Closing as per design
