### ISSUE TITLE
Does this work for DoD in IL5?

### ISSUE THREAD

**Issue by MSGRRojas** [pnp/pnpassessment#13]
Wasn't able to make this work in DoD.  Have you been able to make it work?  Also...will it work for GCC as well?

**Comment by jansenbe** [comment]
Hey @MSGRRojas , did you do the configuration needed for DoD? See https://pnp.github.io/pnpassessment/using-the-assessment-tool/configuration.html#cloud-environment-configuration. 

Feel free to contact me via bjansen@microsoft.com to troubleshoot whenever the above recommendation does not work

**Comment by jansenbe** [comment]
@MSGRRojas : did you manage to get the assessment tool working?

**Comment by MSGRRojas** [comment]
I’m heading back onsite to my DoD environment tomorrow. Let you know :-)

Thank You
________________________________

**Comment by jansenbe** [comment]
@MSGRRojas : can this one be closed?

**Comment by MSGRRojas** [comment]
Yes.  Sorry
