### ISSUE TITLE
Problem when running Assessment - Assessment job not started due to error: Microsoft Graph service exception

### ISSUE THREAD

**Issue by PRusakPL** [pnp/pnpassessment#18]
Hi,

After announcement about deprecating SP2013 Workflows - I wanted to use Assessment tool to run it in Workflow mode.

I receive following error:
**Assessment job not started due to error: Microsoft Graph service exception**
![image](https://user-images.githubusercontent.com/61137411/232674885-b2348c6f-996b-4027-bf1e-2ac37728c031.png)

I tried to use either Interactive or Device --authmode 
I am loging in with account which has SharePoint Admin role (so should have Full Control rights to all SP Site Collections)
In our tenant we have configured "PnP Management Shell" application - with Global Admin consent (see below needed permissions)
![image](https://user-images.githubusercontent.com/61137411/232674422-5903cde9-ea28-4652-be0e-5f0f4d36efbd.png)

How I can investigate more details about potential problem, or maybe you can already know what problem I might have?
Any tips / hints would be really appreciated.
Thanks in advance

**Comment by ValleRLess** [comment]
Were you able to get this resolved. I'm also getting the same error message. Thanks in advanced.

**Comment by jansenbe** [comment]
@PRusakPL , @ValleRLess : please see https://pnp.github.io/pnpassessment/workflow/requirements.html#permission-requirements for the needed permissions. The assessment tool requires both Graph and SharePoint Online permissions.

**Comment by PRusakPL** [comment]
I managed to solve the issue by creating dedicated Azure App registration and assigning appropriate permissions (SharePoint Online and Graph)
Initially I understood (reading below paragraph from documentation) that tool can work without custom App Registration - with default "PnP Management Shell" application (but it cannot - as required permissions are missing for this app if you installed this for PnP Powershell)
![image](https://user-images.githubusercontent.com/61137411/233633196-b2043acf-c80b-46cb-a137-ad73cc9d612c.png)

In the end IMHO this paragraph should disappear from documentation - as this might confuse others too.

**Comment by jansenbe** [comment]
Thanks for the feedback, I'll update the docs!
