### ISSUE TITLE
Assessment tool stops at 70%

### ISSUE THREAD

**Issue by mrivera4** [pnp/pnpassessment#23]
Has anyone had any issues with the assessment tool not processing beyond a certain percentage of sites?  I have tried to run the assessment tool twice on my environment and both times it stopped at 70%, and never proceeded beyond that even after letting run for a couple of weeks.  Are there any logs I could take a look at?  Any suggestions as to how I can get it to run all the way through?

**Comment by jansenbe** [comment]
Hi @mrivera4 , you can inspect if the assessment is still running via checking the log files. If not there's an option to pause it and restart. If for some reason pausing isn't working you can always terminate all the microsoft365-assessment.exe processes and then restart the assessment you were running, it should then continue with the remaining site collections. See https://pnp.github.io/pnpassessment/using-the-assessment-tool/assess-operations.html#im-scanning-a-huge-number-of-site-collections-and-the-assessment-seems-to-be-stuck-what-should-i-do for more documentation on how to that.

**Comment by jansenbe** [comment]
@mrivera4 : I'm closing this issue per no response, if this still is a problem for you then please re-open or create a new issue.
