### ISSUE TITLE
Environment setting in the appsettings.json file does not seem to be working for GCC High

### ISSUE THREAD

**Issue by dmacgr01** [pnp/pnpassessment#25]
I'm trying to run the InfoPath assessment and it doesn't seem to import the environment settings defined in the appsettings.json file which is located in the same folder as the exe file or there is an issue when we try using the cert method, but I am unsure that that issue would be.

The Azure app is setup and granted the following permissions:
![InfoPathAssessmentAPIPermissions](https://github.com/pnp/pnpassessment/assets/138524752/0e950a3c-b83e-4ab1-9c1c-2e503bb51036)

The appsettings.json file contains the following:
```
{
  "PnPCore": {
    "Environment": "USGovernmentHigh"
  },
  "CustomSettings": {
    "Environment": "USGovernmentHigh"
  }
}
```
When I try to run the start command it errors expecting a tenant domain or GUID whether I pass one or not:
![AssessmentError](https://github.com/pnp/pnpassessment/assets/138524752/a7ebaad7-6b33-4966-97b4-cd07519502d8)

When I pull the config it does not reflect the environment settings as I would expect and instead only shows the default port:
![AssessmentConfig](https://github.com/pnp/pnpassessment/assets/138524752/c6b8b941-d2aa-4457-a71c-87a9a30911af)

Now, I know it is reading the config file because when I intentionally malformed the json file, it crashed:
![AssessmentCrash](https://github.com/pnp/pnpassessment/assets/138524752/b29f3b91-b5da-4856-9b05-e3b89cd00071)

I know the Azure app is working as I was able to get results via the interactive and sitelist commands:
![AssessmentWorks](https://github.com/pnp/pnpassessment/assets/138524752/4dfc3561-6fb6-4200-8699-2ceb2955eccf)

**Comment by jansenbe** [comment]
@dmacgr01 : I'm currently OOF, will look at this next week when I'm back

**Comment by jansenbe** [comment]
Hi @dmacgr01 ,

The code was not yet using the tenantId (either the passed in one or the automatically detected one) when a non standard cloud was used (see https://github.com/pnp/pnpassessment/blob/main/src/PnP.Scanning/PnP.Scanning.Core/Authentication/AuthenticationManager.cs#L245-L283). I'll create a fix and add a beta drop of the assessment tool for you to test, as I don't have access to USGov tenants I appreciate it if you can give the beta drop a try and let me know.

**Comment by jansenbe** [comment]
@dmacgr01 : Here's the link to the beta version containing the mentioned fix: https://github.com/pnp/pnpassessment/releases/tag/v1.6.0-beta-windows

**Comment by dmacgr01** [comment]
I tested it out both with and without the tenantid and get the below error:
You are using the latest version 1.6.0

Connecting Microsoft 365 Assessment on port 25010...
No running Microsoft 365 Assessment found, starting one...
OK
Initializing authentication
Starting the Microsoft 365 Assessment
Microsoft 365 Assessment authentication initialized
**_Assessment job not started due to error: Microsoft Graph service exception_** 

Looking at the logs I see that the get request seems to be duplicating the **graph.microsoft.us/v1.0** endpoint in the get requests:
2023-07-10 16:32:21.179 +00:00 [INF] Sending HTTP request GET "https://graph.microsoft.us/v1.0/sites?$select=sharepointIds,id,webUrl,displayName,root"
2023-07-10 16:32:21.784 +00:00 [INF] Received HTTP response headers after 605.4818ms - 200
2023-07-10 16:32:21.785 +00:00 [INF] End processing HTTP request after 606.3426ms - 200
2023-07-10 16:32:21.811 +00:00 [INF] Start processing HTTP request GET "https://graph.microsoft.us/v1.0/https://graph.microsoft.us/v1.0/sites?$select=sharepointIds%2cid%2cwebUrl%2cdisplayName%2croot&$skiptoken=UG*******Q4"
2023-07-10 16:32:21.811 +00:00 [INF] Sending HTTP request GET "https://graph.microsoft.us/v1.0/https://graph.microsoft.us/v1.0/sites?$select=sharepointIds%2cid%2cwebUrl%2cdisplayName%2croot&$skiptoken=UG*******Q4"
2023-07-10 16:32:21.813 +00:00 [INF] Received HTTP response headers after 1.8792ms - 400
2023-07-10 16:32:21.813 +00:00 [INF] End processing HTTP request after 2.2799ms - 400
2023-07-10 16:32:21.828 +00:00 [ERR] Error starting assessment job: Microsoft Graph service exception
HttpResponseCode: 400
Code: BadRequest
Message: Resource not found for the segment 'https:'.
ClientRequestId: 95xxxxxx-xxxx-xxxx-xxxx-xxxxxxd5
date: 2023-07-10T16:32:21
client-request-id: 95xxxxxx-xxxx-xxxx-xxxx-xxxxxxd5

**Comment by jansenbe** [comment]
@dmacgr01 : thanks for testing, seems there's something going wrong with iterating over the sites to assess. I'll have a look, but as an immediate workaround you can consider using the `--sitesfile` option (see https://pnp.github.io/pnpassessment/using-the-assessment-tool/assess-start.html#scoping-via---sitesfile) to tell the assessment tool which site collections to assess.

**Comment by dmacgr01** [comment]
Yep using the sites file is how we got it to work. I'll be happy to test again once you are ready.
Thank you!

**Comment by dmacgr01** [comment]
@jansenbe: I have tested it with and without the tenant ID and both work as expected now. I even created the reports for them to make sure.
Thanks for your efforts!

**Comment by jansenbe** [comment]
Awesome update @dmacgr01 , thanks for testing this!
