### ISSUE TITLE
powerBI querie are in missing a column

### ISSUE THREAD

**Issue by karimzaki** [pnp/pnpassessment#26]
as example this shall be (19 not 18)
= Csv.Document(File.Contents("C:\assessmentout\syntexcontenttypeoverview.csv"),[Delimiter=",", Columns=19, Encoding=1252, QuoteStyle=QuoteStyle.None])

and the following shall be 12 not 11 cause you are missing one column
= Csv.Document(File.Contents("C:\assessmentout\syntexcontentfields.csv"),[Delimiter=",", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None])

**Comment by jansenbe** [comment]
@karimzaki : are you using the beta version? The report update for that one is still pending, so that might explain. Would recommend using 1.5 for now.

**Comment by karimzaki** [comment]
i m using instructions from here 
https://pnp.github.io/pnpassessment/index.html

**Comment by jansenbe** [comment]
@karimzaki : please try with 1.5 (https://github.com/pnp/pnpassessment/releases/tag/v1.5.0-windows). Ensure you've killed all running microsoft365-assesment.exe processes before launching the 1.5 version.

**Comment by jansenbe** [comment]
Closing per no response
