### ISSUE TITLE
Microsoft 365 Assessment fails to run: "Unhandled exception: System.Exception: Microsoft 365 Assessment tool did not start timely"

### ISSUE THREAD

**Issue by netadmin-grrl** [pnp/pnpassessment#27]
Running version 1.6.0, on Windows 10, 22H2, build 19045.3693.  
App set up & configured in Entra (Azure). 
Self-signed cert generated per docs and uploaded to registered app.
Verified in Resource Monitor that no other app was using port 25010.
Made sure that there were no "rogue" instances of application running.

Odd thing is, the log shows everything is OK.

```
2023-12-07 10:12:43.332 -05:00 [INF] Starting Microsoft 365 Assessment on port 25010
2023-12-07 10:12:43.576 -05:00 [INF] Started Microsoft 365 Assessment on port 25010
2023-12-07 10:12:43.638 -05:00 [INF] User profile is available. Using 'C:\Users\xxxxxx\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
2023-12-07 10:12:43.970 -05:00 [INF] Now listening on: http://localhost:25010
2023-12-07 10:12:43.975 -05:00 [INF] Application started. Press Ctrl+C to shut down.
2023-12-07 10:12:43.976 -05:00 [INF] Hosting environment: Production
2023-12-07 10:12:43.977 -05:00 [INF] Content root path: C:\Users\xxxxxx\Downloads\microsoft365assessment
```

```
Execute a command (<enter> to quit):
config

┌──────────┬───────┬─────────┬───────────────────────┐
│ Setting  │ Value │ Default │ appsettings.json path │
├──────────┼───────┼─────────┼───────────────────────┤
│ Port     │ 25010 │ 25010   │ CustomSettings:Port   │
└──────────┴───────┴─────────┴───────────────────────┘

Execute a command (<enter> to quit):
```

Complete error output:

```
Execute a command (<enter> to quit):
status

Connecting Microsoft 365 Assessment on port 25010...
No running Microsoft 365 Assessment found, starting one...
Unhandled exception: System.Exception: Microsoft 365 Assessment tool did not start timely
   at PnP.Scanning.Process.Services.ScannerManager.WaitForScannerToBeUpAsync()
   at PnP.Scanning.Process.Services.ScannerManager.LaunchScannerAsync()
   at PnP.Scanning.Process.Services.ScannerManager.GetScannerClientAsync()
   at PnP.Scanning.Process.Commands.StatusCommandHandler.HandleStatusAsync()
   at PnP.Scanning.Process.Commands.StatusCommandHandler.<Create>b__2_0()
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext )
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()

Execute a command (<enter> to quit):
```

**Comment by jansenbe** [comment]
@netadmin-grrl : what happens when you type a command at the prompt, e.g. list? Same error?

How many microsoft365-assessment.exe processes are running after you saw the error?

**Comment by netadmin-grrl** [comment]
Just the one.
![m365-assessment-ts](https://github.com/pnp/pnpassessment/assets/153206832/614cbd87-6ace-4207-a76c-96a2fce995ab)

**Comment by jansenbe** [comment]
@netadmin-grrl : thanks for confirming that, so the process never started. As I've no repro of this issue it's hard to fix, hence I'm building a debug build that logs more information. Hope you can try that?

**Comment by netadmin-grrl** [comment]
Sure can! I'm OOO next week, so if you don't hear from me in that time frame, that's why.

**Comment by netadmin-grrl** [comment]
Made sure that no additional "rogue" processes were running, and then 2x-clicked on the .exe:

You are using the latest version 1.6.1

                 __  __   _                                        __   _       _____    __     ____
                |  \/  | (_)   ___   _ __    ___    ___    ___    / _| | |_    |___ /   / /_   | ___|
                | |\/| | | |  / __| | '__|  / _ \  / __|  / _ \  | |_  | __|     |_ \  | '_ \  |___ \
                | |  | | | | | (__  | |    | (_) | \__ \ | (_) | |  _| | |_     ___) | | (_) |  ___) |
                |_|  |_| |_|  \___| |_|     \___/  |___/  \___/  |_|    \__|   |____/   \___/  |____/

                            _                                                                _
                           / \     ___   ___    ___   ___   ___   _ __ ___     ___   _ __   | |_
                          / _ \   / __| / __|  / _ \ / __| / __| | '_ ` _ \   / _ \ | '_ \  | __|
                         / ___ \  \__ \ \__ \ |  __/ \__ \ \__ \ | | | | | | |  __/ | | | | | |_
                        /_/   \_\ |___/ |___/  \___| |___/ |___/ |_| |_| |_|  \___| |_| |_|  \__|


Execute a command (<enter> to quit):
list

Connecting Microsoft 365 Assessment on port 25010...
No running Microsoft 365 Assessment found, starting one...
Microsoft 365 Assessment tool did not start timely
OK
Unhandled exception: Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while unable to establish HTTP/2 connection.", DebugException="System.Net.Http.HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while unable to establish HTTP/2 connection.")
 ---> System.Net.Http.HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while unable to establish HTTP/2 connection.
   at System.Net.Http.HttpConnectionPool.ThrowGetVersionException(HttpRequestMessage request, Int32 desiredVersion, Exception inner)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
   --- End of inner exception stack trace ---
   at PnP.Scanning.Process.Commands.ListCommandHandler.HandleStartAsync(Boolean running, Boolean paused, Boolean finished, Boolean terminated)
   at PnP.Scanning.Process.Commands.ListCommandHandler.<Create>b__7_0(Boolean running, Boolean paused, Boolean finished, Boolean terminated)
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()

Execute a command (<enter> to quit):

![m365-assessment-ts-2](https://github.com/pnp/pnpassessment/assets/153206832/42a62bc5-4ca0-4070-96d3-eeda72956257)

**Comment by jansenbe** [comment]
@netadmin-grrl : you happen to behind a proxy server or have the environment variables `http_proxy` or  `https_proxy` set?

**Comment by netadmin-grrl** [comment]
Possibly some monitoring software. <grr>
Would this be the same value as set in "Local Area Network (LAN) Settings" -> Proxy Server?

**Comment by jansenbe** [comment]
yes that's true, or via environment variables

**Comment by netadmin-grrl** [comment]
OK then, it's monitoring software, probably Forcepoint. I thought it could be the culprit but wasn't sure until the logs (whoo hoo). Let me see if I can run the debug version on a machine without it and get back to you.

**Comment by jansenbe** [comment]
Alternative solution could also be excluding localhost traffic from the proxy via adding the environment variable `no_proxy` with value `localhost,127.0.0.1`

**Comment by netadmin-grrl** [comment]
Good news/bad news: it looks like running it on a computer that doesn't have the FP software is working, BUT my cert isn't getting loaded, doesn't like the path info passed to --certpath . (Verified thumbprint ID in Azure/Registered Apps.)

**Comment by netadmin-grrl** [comment]
Running tool from my system and still having certificate errors. 
If I install cert to Root and use "--certpath "My|CurrentUser|xxxx" I get "Certificate could not be loaded using this path information".
If I install cert to Root and use "--certpath "My|CurrentUser|Root|xxxx" I get "Certificate could not be loaded using this path information".
If I install cert to Personal, I get "The certificate certificate does not have a private key."
Think I may just re-do the whole certificate thing. I'm not that good at them, and this was 2 weeks ago, so I don't even remember exactly how I set it up.

**Comment by jansenbe** [comment]
@netadmin-grrl : you need to export the cert with it's private key into a PFX file from the original machine and re-import on the new machine. Launch `certmgr.msc` in Windows, select the Personal -> Certificates node and choose All Tasks -> Import. To grab the thumbprint that's easiest done from the Certificate page from your Azure AD app.

Once you've upload the cert with private key and have the thumbprint use like this: --certpath "My|CurrentUser|b133d1cb4d19ce539986c7ac67de005481084c84" where the last part is to be replaced with your thumbprint

**Comment by jansenbe** [comment]
@netadmin-grrl : once you're back from vacation, it would be good if you could test version 1.6.2 and see if that works on your default setup, so with ForcePoint

**Comment by netadmin-grrl** [comment]
I'll work on this today and report back.

**Comment by netadmin-grrl** [comment]
Still no joy :-(.  I recreated the Azure AD app as I don't think I configured the cert stuff right the last time. I don't see any extra log files in the directory along with the executable. Anyhow to the fun (applicationId and certpath variables sanitized for public consumption):

PS C:\Users\mmacenroe\Downloads\microsoft365assessment> .\microsoft365-assessment.exe start --mode AddInsACS --authmode application --tenant oneidacountygov.sharepoint.com --applicationid xxxxxx --certpath "My|CurrentUser|yyyyyy"

You are using the latest version 1.6.2

Connecting Microsoft 365 Assessment on port 25010...
OK

Initializing authentication
Starting the Microsoft 365 Assessment
Assessment job not started due to error:


PS C:\Users\mmacenroe\Downloads\microsoft365assessment> .\microsoft365-assessment.exe

You are using the latest version 1.6.2

                 __  __   _                                        __   _       _____    __     ____
                |  \/  | (_)   ___   _ __    ___    ___    ___    / _| | |_    |___ /   / /_   | ___|
                | |\/| | | |  / __| | '__|  / _ \  / __|  / _ \  | |_  | __|     |_ \  | '_ \  |___ \
                | |  | | | | | (__  | |    | (_) | \__ \ | (_) | |  _| | |_     ___) | | (_) |  ___) |
                |_|  |_| |_|  \___| |_|     \___/  |___/  \___/  |_|    \__|   |____/   \___/  |____/

                            _                                                                _
                           / \     ___   ___    ___   ___   ___   _ __ ___     ___   _ __   | |_
                          / _ \   / __| / __|  / _ \ / __| / __| | '_ ` _ \   / _ \ | '_ \  | __|
                         / ___ \  \__ \ \__ \ |  __/ \__ \ \__ \ | | | | | | |  __/ | | | | | |_
                        /_/   \_\ |___/ |___/  \___| |___/ |___/ |_| |_| |_|  \___| |_| |_|  \__|


Execute a command (<enter> to quit):
start --mode AddInsACS --authmode application --tenant oneidacountygov.sharepoint.com --applicationid xxxxxx --certpath "My|CurrentUser|yyyyyy"

Connecting Microsoft 365 Assessment on port 25010...
OK

Initializing authentication
Starting the Microsoft 365 Assessment
Assessment job not started due to error:

Execute a command (<enter> to quit):

PS C:\Users\mmacenroe\Downloads\microsoft365assessment>

**Comment by jansenbe** [comment]
@netadmin-grrl : strange there's no error, so no log file in the .exe folder and no sub folder created for the assessment then?

**Comment by netadmin-grrl** [comment]
Correct. I found that strange as well.

Michelle MacEnroe
Systems and Networking Engineer
Oneida County Information Technology

800 Park Avenue
Utica, NY 13501
***@***.******@***.***>
p. 315-798-5824
m. 315-796-4462

**Comment by jansenbe** [comment]
@netadmin-grrl : but using a machine without ForcePoint works?

**Comment by netadmin-grrl** [comment]
Yep. My colleague gets annoyed when we blanket-blame and blanket-bomb FP but it is a piece of garbage.
I removed it from my old laptop, and went thru all the steps again to set up the Azure app, etc (just to be sure).  Then magic happened!

```
c:\Users\admin\Downloads\m365assessment>microsoft365-assessment.exe start --mode syntex --authmode application --tenant xyz.sharepoint.com --applicationid dc0029b4-5f3b-47f1-8cf8-865c198a88af --certpath "My|CurrentUser|6CF47248E5A14503CA9075BDE393552D67BBBC27" --syntexfull

You are using the latest version 1.6.2

Connecting Microsoft 365 Assessment on port 25010...
No running Microsoft 365 Assessment found, starting one...
OK

Initializing authentication
Starting the Microsoft 365 Assessment
Microsoft 365 Assessment authentication initialized
Enumerated 144 site collections for tenant xyz.sharepoint.com
Sites to assess are defined
Sites to assess are queued up. Assessment id = 54dc2753-8323-4e40-9149-d268f3502654

Microsoft 365 Assessment is running!
Use the status command to get realtime feedback
Use the list command to an overview of all Microsoft 365 Assessments

c:\Users\admin\Downloads\m365assessment>

c:\Users\admin\Downloads\m365assessment>microsoft365-assessment.exe status

You are using the latest version 1.6.2

Connecting Microsoft 365 Assessment on port 25010...
OK

Live running Microsoft 365 Assessment status. Press ESC to exit

┌──────────────────┬──────┬────────┬──────────┬─────────┬───────────────┬──────────────────┐
│        Id        │ Mode │ Status │ Progress │ Retries │ Session start │ Session duration │
├──────────────────┼──────┼────────┼──────────┼─────────┼───────────────┼──────────────────┤
│ No running scans │      │        │          │         │               │                  │
└──────────────────┴──────┴────────┴──────────┴─────────┴───────────────┴──────────────────┘

c:\Users\admin\Downloads\m365assessment>microsoft365-assessment.exe list

You are using the latest version 1.6.2

Connecting Microsoft 365 Assessment on port 25010...
OK
┌───────────────────────────────────┬────────┬──────────┬────────────────┬──────────────────────┬──────────────────────┐
│ Id                                │ Mode   │  Status  │    Progress    │ Started at           │ Ended at             │
├───────────────────────────────────┼────────┼──────────┼────────────────┼──────────────────────┼──────────────────────┤
│ 54dc2753-8323-4e40-9149-d268f3502 │ Syntex │ Finished │ 144/144 (100%) │ 1/17/2024 3:08:44 PM │ 1/17/2024 3:12:53 PM │
│ 654                               │        │          │                │                      │                      │
└───────────────────────────────────┴────────┴──────────┴────────────────┴──────────────────────┴──────────────────────┘

c:\Users\admin\Downloads\m365assessment>

c:\Users\admin\Downloads\m365assessment>microsoft365-assessment.exe start --mode AddInsACS --authmode application --tenant xyz.sharepoint.com --applicationid dc0029b4-5f3b-47f1-8cf8-865c198a88af --certpath "My|CurrentUser|6CF47248E5A14503CA9075BDE393552D67BBBC27"

You are using the latest version 1.6.2

Connecting Microsoft 365 Assessment on port 25010...
OK

Initializing authentication
Starting the Microsoft 365 Assessment
Microsoft 365 Assessment authentication initialized
Enumerated 144 site collections for tenant xyz.sharepoint.com
Sites to assess are defined
Sites to assess are queued up. Assessment id = ec6d378a-6f0d-451e-a6df-0ab5df7448ad

Microsoft 365 Assessment is running!
Use the status command to get realtime feedback
Use the list command to an overview of all Microsoft 365 Assessments

c:\Users\admin\Downloads\m365assessment>microsoft365-assessment.exe status

You are using the latest version 1.6.2

Connecting Microsoft 365 Assessment on port 25010...
OK

Live running Microsoft 365 Assessment status. Press ESC to exit
┌──────────────────────────────────────┬───────────┬─────────┬──────────────┬─────────┬──────────────────────┬──────────────────┐
│                  Id                  │   Mode    │ Status  │   Progress   │ Retries │    Session start     │ Session duration │     Id
├──────────────────────────────────────┼───────────┼─────────┼──────────────┼─────────┼──────────────────────┼──────────────────┤┼───────────│ f7e11978-b62f
│ f7e11978-b62f-41b7-8344-41d7979934cc │ AddInsACS │ Queued  │  0/144 (0%)  │  0 / 0  │ 1/17/2024 3:26:18 PM │   00:00:08:36    │c6d378a-6f0d-451e-a6df-0ab5
│ ec6d378a-6f0d-451e-a6df-0ab5df7448ad │ AddInsACS │ Running │ 42/144 (29%) │  0 / 0  │ 1/17/2024 3:34:30 PM │   00:00:00:24    │
└──────────────────────────────────────┴───────────┴─────────┴──────────────┴─────────┴──────────────────────┴──────────────────┘:30 PM │   0
                                                                                                                                 ─


c:\Users\admin\Downloads\m365assessment>microsoft365-assessment.exe status

You are using the latest version 1.6.2

Connecting Microsoft 365 Assessment on port 25010...
OK

Live running Microsoft 365 Assessment status. Press ESC to exit

┌──────────────────────────────────────┬───────────┬─────────┬───────────────┬─────────┬──────────────────────┬──────────────────┐
│                  Id                  │   Mode    │ Status  │   Progress    │ Retries │    Session start     │ Session duration │
├──────────────────────────────────────┼───────────┼─────────┼───────────────┼─────────┼──────────────────────┼──────────────────┤
│ f7e11978-b62f-41b7-8344-41d7979934cc │ AddInsACS │ Queued  │  0/144 (0%)   │  0 / 0  │ 1/17/2024 3:26:18 PM │   00:00:09:11    │
│ ec6d378a-6f0d-451e-a6df-0ab5df7448ad │ AddInsACS │ Running │ 124/144 (86%) │  0 / 0  │ 1/17/2024 3:34:30 PM │   00:00:00:59    │
└──────────────────────────────────────┴───────────┴─────────┴───────────────┴─────────┴──────────────────────┴──────────────────┘

c:\Users\admin\Downloads\m365assessment>

```

**Comment by jansenbe** [comment]
Closing this one, the assessment tool does not support custom proxy settings...if you're blocked due to this the advice is to run the assessment from a machine that can bypass your proxy.
