### ISSUE TITLE
Bolonyokte??

### ISSUE THREAD

**Issue by nattomatto** [pnp/pnpassessment#30]
My SOC just quarantined me after attempting to download the latest release that the file matched the bolonykte trojan…. No clue if it is a false positive or if the file has been compromised.

**Comment by jansenbe** [comment]
The official versions are code signed and so far we've never received any of such notifications. The code is also fully open source, so hard to hide anything. Only MSFT employees have been reviewing and merging PR's...so I'm quite confident this is a false positive.

**Comment by nattomatto** [comment]
I am quite certain it is, and I confirmed this with my SOC.  I wanted the community to be aware unless anyone else has an issue with their Security or Virus team.

**Comment by jansenbe** [comment]
@nattomatto : can you send me more information about the tools you're using and links to the discovered issue? Feel free to send to bjansen@microsoft.com if you can't share here. I don't see how our .NET application is a trojan...maybe the software you're using is confused as the .NET single exe contains multiple files? You can try to download an earlier version of this tool and see if you get similar results.

**Comment by jansenbe** [comment]
I've ran an analysis of the latest version and it returned clean: https://www.hybrid-analysis.com/sample/b321c6fed668fa213c8db2191ee68ceac76f46ea630506b623fb78ddb242f6fb

**Comment by jansenbe** [comment]
I'm closing this one as it's a false positive. Feel free to send me more details in case you have them
