### ISSUE TITLE
AddInsACS assessment queued

### ISSUE THREAD

**Issue by Zetkai84** [pnp/pnpassessment#32]
Hi,

When trying to start an AddInsACS assessment got the following error: "Assessment job not started due to error: Invalid URI: The format of the URI could not be determined.", when running list command the job shows as queued, any clues? (I'm suspecting that could have some to do with Vanity URLs, my tenant uses them but InfoPath and Workflow scans works fine).

Please assist

Thanks!
![Error](https://github.com/pnp/pnpassessment/assets/63333464/41648cc2-6d16-41e5-89b1-a88d7ed7bf4e)

**Comment by jansenbe** [comment]
@Zetkai84 : could there be a wrongly formatted url in your sites file (lastsitelist.txt)?

**Comment by Zetkai84** [comment]
Got the same error even if I don't use site list file, also works fine for Workflow or InfoPath assessment. I've set up settings file as My tenant is using vanity urls

**Comment by jansenbe** [comment]
@Zetkai84 : can you share the command line used and the created log file? If these can't be shared publicly then send them to bjansen@microsoft.com.

**Comment by jansenbe** [comment]
closing per offline discussion with @Zetkai84 .
