### ISSUE TITLE
M365 assessment tool report doesn't provide option for the 'SharePoint add-in and ACS' scan mode

### ISSUE THREAD

**Issue by nikhilshankarsingh** [pnp/pnpassessment#33]
AddInsACS' scan mode is not available in version 1.6.0. Does that command not be incorporated, or is there something I need to include?

C:\...\00microsoft365assessment>microsoft365-assessment.exe start --mode AddInsACS --tenant zzz.sharepoint.com --sitesfile "C:\...\00microsoft365assessment\sites.txt" --authmode Application --applicationid <> --certpath "My|CurrentUser|<>"

**You are using the latest version 1.6.0**

**Cannot parse argument 'AddInsACS' for option '--mode' as expected type 'PnP.Scanning.Core.Services.Mode'. Did you mean one of the following?
Classic
InfoPath
Syntex
Workflow**

Description:
  Starts a new Microsoft 365 Assessment

Usage:
  microsoft365-assessment start [options]

Options:
  --mode <Classic|InfoPath|Syntex|Workflow> (REQUIRED)    Assessment mode [default: Syntex]
  --tenant <tenant> (REQUIRED)                            Name of the tenant that will be assessed (e.g.
                                                          contoso.sharepoint.com)
  --siteslist <siteslist>                                 List with site collections to assess
  --sitesfile <sitesfile>                                 File containing a list of site collections to assess
  --authmode <Application|Device|Interactive> (REQUIRED)  Authentication mode used for the Microsoft 365 Assessment
                                                          [default: Interactive]

**Comment by jansenbe** [comment]
@nikhilshankarsingh : that's weird, we've hundreds of customers using version 1.6.0 and using mode `AddInsACS`. Can you cross check all microsoft365-assessment.exe processes are killed, then download again from https://github.com/pnp/pnpassessment/releases/download/v1.6.0-windows/microsoft365-assessment.exe and double click the .exe. Once loaded type `start --help` and check the output

![image](https://github.com/pnp/pnpassessment/assets/7451219/db07f4d1-2d3a-4164-b328-1fef7529b99e)

**Comment by nikhilshankarsingh** [comment]
Thanks @jansenbe, downloading the .exe tool again has helped. I can now see the "AddInsACS" mode. Really appreciated your quick response.

C:\...\00microsoft365assessment>microsoft365-assessment.exe start --help

**You are using the latest version 1.6.0**

Description:
  Starts a new Microsoft 365 Assessment

Usage:
  microsoft365-assessment start [options]

Options:
  --mode <**AddInsACS**|Classic|InfoPath|Syntex|Workflow>     Assessment mode [default: Syntex]
  (REQUIRED)
  --tenant <tenant> (REQUIRED)                            Name of the tenant that will be assessed (e.g.
                                                          contoso.sharepoint.com)
  --siteslist <siteslist>                                 List with site collections to assess
  --sitesfile <sitesfile>                                 File containing a list of site collections to assess

**Comment by nikhilshankarsingh** [comment]
worked well! thanks
