### ISSUE TITLE
ACS Assessment tool failing in GCC with below error even after setting change in json

### ISSUE THREAD

**Issue by rachoksh** [pnp/pnpassessment#34]
Error: 
Microsoft.Identity.Client.MsalServiceException: AADSTS90038: Tenant 'xxxxxx-258b-45b4-a519-xxxxx' request is being redirected to the National Cloud 'MicrosoftOnline.COM'.

Please help with correct steps to run ACS assessment in GCC tenant. 

Thanks

**Comment by rachoksh** [comment]
This is what is in the json file: 
{
  "PnPCore": {
    "Environment": "USGovernment"
  },
  "CustomSettings": {
    "Environment": "USGovernment",    
    "Port": 7887,
    "AdminCenterUrl": "https://gcctenantname-admin.sharepoint.com",
    "MySiteHostUrl": "https://gcctenantname-my.sharepoint.com"
  }
}

**Comment by jansenbe** [comment]
@rachoksh : can you try with just this:

{
"PnPCore": {
"Environment": "USGovernment"
},
"CustomSettings": {
"Environment": "USGovernment",
}
}

**Comment by jansenbe** [comment]
@rachoksh : did it work with the simplified configuration file?

**Comment by rachoksh** [comment]
I will test and get back to you. Thanks

**Comment by jansenbe** [comment]
@rachoksh : also test without config file, doing a test from my side with a GCC tenant showed it worked without specific configuration if it's hosted on the sharepoint.com domain

**Comment by jansenbe** [comment]
@rachoksh : closing this one, docs have been updated to reflect that config is not needed for GCC, it however is for GCCHigh and others
