### ISSUE TITLE
cannot start assesment

### ISSUE THREAD

**Issue by vilmarcikpn** [pnp/pnpassessment#37]
I am getting the following error:

"Assessment job not started due to error: Microsoft Graph service exception"
I am connecting in applicaton mode, with a certificate and password. The same issue comes when using interactive login.

Full output:

You are using the latest version 1.6.2

Connecting Microsoft 365 Assessment on port 25010...
OK

Initializing authentication
Starting the Microsoft 365 Assessment
Microsoft 365 Assessment authentication initialized
Enumerate30381 site collections for tenant kpnbv.sharepoint.com
Sites to assess are defined
**Assessment job not started due to error: Microsoft Graph service exception**

**Comment by jansenbe** [comment]
@vilmarcikpn : did you grant **and consent** the proper permissions. See https://pnp.github.io/pnpassessment/using-the-assessment-tool/setupauth.html#creating-an-azure-ad-application-using-the-azure-ad-portal for the generic instructions, each module requires slightly different permissions, here's the one for the AddInsACS module: https://pnp.github.io/pnpassessment/addinsacs/requirements.html#permission-requirements

**Comment by jansenbe** [comment]
Thanks for the update @vilmarcikpn . I'm closing this issue then.
