### ISSUE TITLE
Reports are coming out blank after running "SharePoint Add-In and Azure ACS Assessment" tool

### ISSUE THREAD

**Issue by spcodehelp** [pnp/pnpassessment#38]
We tried to run "SharePoint Add-In and Azure ACS Assessment" tool against one site collection where we know we have created ClientIDs/Secret.  The reports are coming blank. Appreciate taking time to look into it.

**Comment by jansenbe** [comment]
@spcodehelp : can you cross check you've granted the correct permissions for the app used in the assessment run. See https://pnp.github.io/pnpassessment/addinsacs/requirements.html#permission-requirements. If you've excluded the Application.Read.All scope then no ACS principals will be reported but the run itself will not fail.

**Comment by spcodehelp** [comment]
Hello @jansenbe  - Thank you for your quick response. I have reverified and confirmed that the application has required access as mentioned in the article. Attach is a screenshot for reference:
<img width="940" alt="AppPerms" src="https://github.com/pnp/pnpassessment/assets/57759008/310bc747-f139-4c6d-95e2-35482039464a">

**Comment by jansenbe** [comment]
@spcodehelp : did the run have any errors (see last tab of the Power BI report). Can you try adding a new (not expired) ACS principal to that site (via appregnew.aspx and appinv.aspx) and check if that shows up?

**Comment by jansenbe** [comment]
@spcodehelp : that's all weird. Can you share the log files with me (bjansen@microsoft.com)

**Comment by jansenbe** [comment]
Closing this one, issue was related to not using the correct setup with vanity urls
