### ISSUE TITLE
Microsoft 365 assessment tool

### ISSUE THREAD

**Issue by takiguchiyuka** [pnp/pnpassessment#40]
Using the Microsoft 365 assessment tool,
I would like to check the usage status of SharePoint Add-ins in my tenant.
https://learn.microsoft.com/ja-jp/sharepoint/dev/sp-add-ins/retirement-payment-for-add-ins#microsoft-365-assessment-tool

I ran .\microsoft365-assessment.exe and it says "An error occurred while reporting for this Microsoft 365 assessment: The assessment was "skimmed""
"Data cannot be exported because it has not been terminated or paused" is displayed. I hope it gets resolved.

=================================================
Preparations were carried out as follows.

A. Registering your application with Microsoft Entra ID
-------------------------------------------------- -
We issued a self-certificate and registered the application with Microsoft Entra ID by referring to the public information below, "Set up an Azure AD app for app-only access."
 
Title: Grant access using Azure AD app-only - Set up an Azure AD app for app-only access -
Address: https://learn.microsoft.com/ja-jp/sharepoint/dev/solution-guidance/security-apponly-azuread#setting-up-an-azure-ad-app-for-app-only-access

*Access permission is granted as follows.
Microsoft Graph -> Application Permissions -> Sites.Read.All and Application.Read.All
SharePoint -> Application permissions -> Site.Read.All

B. Obtain the Microsoft 365 Assessment tool for Windows
-------------------------------------------------- -
Visit the following site and download the latest version of the Microsoft 365 Assessment tool for Windows (microsoft365-assessment.exe) to your work device.
 
Title: Microsoft 365 Assessment tool for Windows
Address: https://github.com/pnp/pnpassessment/releases

Steps to run the tool
----------------
1) Start the command prompt or Windows PowerShell on your work terminal and run the downloaded microsoft365-assessment.exe with the following parameters.
 
.\microsoft365-assessment.exe start --mode AddInsACS --authmode application --tenant <tenant>.sharepoint.com --applicationid <client ID> --certfile "<path to self certificate (.pfx)>" - -certpassword "<self-certificate password>"
 
The values ​​to enter for each parameter are as follows.
tenant: SharePoint domain of the tenant
applicationid: Client ID of the application registered in advance preparation
certfile: Path to the self-certificate (.pfx file) created in advance preparation
certpassword: Password for the self-certificate created in advance preparation
 
(execution example)
.\microsoft365-assessment.exe start --mode AddInsACS --authmode application--tenant contoso.sharepoint.com --applicationid 91a02c15-01b0-448e-9e78-c296b8b14cb8 --certfile "C:\acs.pfx" --certpassword "password"

2) If the tool runs successfully, the Assessment id will be output as shown below, so take note of the value.
 
Initializing authentication
Starting the Microsoft 365 Assessment
Microsoft 365 Assessment authentication initialized
Enumerated 94 site collections for tenant contoso.sharepoint.com
Sites to assess are defined
Sites to assess are queued up. Assessment id = f57da9d4-54d0-4e44-a383-36a0e751e1c3
 
3) Continue running microsoft365-assessment.exe with the following parameters:
 
.\microsoft365-assessment.exe report --id f57da9d4-54d0-4e44-a383-36a0e751e1c3 --mode CsvOnly --path "C:\report"
 
The values ​​to enter for each parameter are as follows.
id: Assessment id output when the tool is successful
path: report output folder

**Comment by jansenbe** [comment]
@takiguchiyuka : please follow these steps to configure the Azure AD application https://pnp.github.io/pnpassessment/using-the-assessment-tool/setupauth.html#creating-an-azure-ad-application-using-the-azure-ad-portal. Each assessment module requires different permissions, in case of AddInsACS the needed permissions are defined here: https://pnp.github.io/pnpassessment/addinsacs/requirements.html#permission-requirements. Based upon your comment you did that. 

Could it simply be that the assessment was stil running? When you launch it it will execute in background, so the fact that the prompt returns does not mean the assessment is done. Use `.\microsoft365-assessment.exe list` to see the status of all assessments, use `.\microsoft365-assessment.exe status` to see the status of the currently running one (if any).

Report creation can only happen when the assessment hass finished.

**Comment by jansenbe** [comment]
Closing per no response. Please re-open if still valid
