### ISSUE TITLE
AddInsACS Assessment stuck as "queued"

### ISSUE THREAD

**Issue by nigelhertz** [pnp/pnpassessment#41]
Hi, I had a 'Syntex' assessment running, and started an 'AddInsACS' assessment while the previous 'Syntex' one was running. The 'AddInsACS' assessment was added to the list, with a status of "Queued".

The 'Syntex' assessment was later terminated, however the 'AddInsACS' has still been sitting as "Queued" for ages now, with no progress.

I then went to a completely different machine, and tried running the same 'AddInsACS' assessment there (using --certfile etc after exporting and copying the pfx). The assessment on this machine is also sitting on "Queued" with no progress. 

Is there any way to either delete these assessments completely, or force them to start running?

On the first machine - it is now 16:46
![image](https://github.com/pnp/pnpassessment/assets/43138116/264b9c28-f714-4aa2-b683-9a00eafdacb5)

On the second machine
![image](https://github.com/pnp/pnpassessment/assets/43138116/81a6429d-ad96-4da4-9607-cec03d48a5c0)

Any help would be appreciated.

**Comment by nigelhertz** [comment]
This can be closed. I didn't realise the queued items were cached folders on the file system. I did run into another issue relating to permissions - the provided powershell script to create the enterprise application missed out on 2 permission sets - these 2 were not created at all.
![image](https://github.com/pnp/pnpassessment/assets/43138116/6973860f-9938-4dee-8542-137ce191e9fd)
A lot of googling later after trawling through logs and getting red herrings, I finally found an obscure article about the issue. Manually added the permissions, and bam - it works. I guess we shouldn't rely on MS provided scripts to actually work.

**Comment by jansenbe** [comment]
@nigelhertz : the requirements for the AddInACS assessment are documented here: https://pnp.github.io/pnpassessment/addinsacs/requirements.html. The sample script configures things for the Syntex module, I do agree we should make that more visible (today it's only in the comment):

![image](https://github.com/pnp/pnpassessment/assets/7451219/2893d9d5-22a1-449d-bbf6-ad9afb10449d)
