### ISSUE TITLE
Preview Image option is not working for few documents in pnp search result filter.

### ISSUE THREAD

**Issue by DharmendraYadav90** [pnp/pnpassessment#42]
Preview Image option is not working for few documents in pnp search result filter.

**Comment by jansenbe** [comment]
@DharmendraYadav90 : is this an issue for this repo?

**Comment by DharmendraYadav90** [comment]
no

**Comment by jansenbe** [comment]
@DharmendraYadav90 : please ask this query then in the pnp search repo: https://github.com/microsoft-search/pnp-modern-search.
