### ISSUE TITLE
Microsoft 365 Assessment Tool Errors attempting to run SharePoint Add/In assessment

### ISSUE THREAD

**Issue by MJ-Apptitude** [pnp/pnpassessment#43]
Microsoft 365 Assessment Tool Errors attempting to run SharePoint Add/In assessment.  Errors received are attached.  I am using the following syntax and woud like to run this on one site initially not the entire tenant.
![Screenshot 2024-02-29 152643](https://github.com/pnp/pnpassessment/assets/161771166/41b25a83-1842-4109-a56e-5bc882919c73)

start --mode AddInsACS --authmode application
--tenant company.sharepoint.com  --applicationid xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx
--siteslist "https://company.sharepoint.com/sites/allcompany38"

**Comment by jansenbe** [comment]
You're missing the --authmode parameter, see https://pnp.github.io/pnpassessment/using-the-assessment-tool/assess-start.html#authentication-configuration

**Comment by MJ-Apptitude** [comment]
Hi thanks for responding but I added the authmode as you can see in the text at the bottom of the screenshot I've tried it with applicationid.  I've also tried it with interactive and still receive errors.

**Comment by jansenbe** [comment]
Oh sorry, missed that one. When using application permissions you also need to specify the certificate to use. See https://pnp.github.io/pnpassessment/using-the-assessment-tool/assess-start.html#specifying-the-certificate-to-use-when-using-application-permissions.

**Comment by MJ-Apptitude** [comment]
Problem turned out to be that all arguments needed to be on the same line before executing. 👍

**Comment by jansenbe** [comment]
@MJ-Apptitude , also looking at the screenshot you've not added all parameters, it should be like this (only added the first params, you'll need to add all)

![image](https://github.com/pnp/pnpassessment/assets/7451219/1f5c746f-c6ce-4417-a7f8-2397418a75b0)
