### ISSUE TITLE
One site failed in assessment

### ISSUE THREAD

**Issue by makmv** [pnp/pnpassessment#48]
Hi, 
I have successfully run the assessment tool and able to get the report fine on all sites but one. I see the reason for failure as below:
could you please advise what might be the reason.

'Setting Web table to status Failed for assessment' 

Can I run the assessment on this single site again using the --authmode as application? or do we have to use the interactive --authmode only.
Thanks in advance.
Mak.

**Comment by jansenbe** [comment]
@makmv: run the assessment for the failing site by adding the --siteslist parameter (see https://pnp.github.io/pnpassessment/using-the-assessment-tool/assess-start.html#scoping-via---siteslist) and then have a look at the created logs files (or share them with me via bjansen@microsoft.com).

**Comment by jansenbe** [comment]
@makmv : did above help?
