### ISSUE TITLE
Multiple queries about the assessment tool

### ISSUE THREAD

**Issue by roguetomato** [pnp/pnpassessment#50]
Hi, I have multiple questions about the assessment tool for Sharepoint Add-in.

1. We have multiple tenants and currently only one tenant (UAT tenant) has the configuration for the Azure AD application for the permission. Would it be possible to execute the tool in PowerShell on a device within the production tenant, with the understanding that it will operate against the UAT tenant environment? Will using the MSOnline module work this setup?

2. Is it strongly recommended to utilise a certificate for authentication instead of a client secret? Will client secret work?

3. How much time does it typically take for the "No running Microsoft 365 Assessment found, starting one... Starting Microsoft 365 Assessment..." process to complete? What could be the reason if the process remains stuck at that stage? I left my device running overnight in an attempt to allow it to finish, but it was still stuck on that process the following day.

**Comment by roguetomato** [comment]
Hi @jansenbe, 

Thanks for your clarifications on my questions 1 and 2 .
Regarding point 3, I consistently encounter this issue whenever I execute the tool. Furthermore, no logs seems to be generated. It could be related to my authentication being on a client secret so I will change that first and I will let you know.

![Screenshot 2024-04-11 094246](https://github.com/pnp/pnpassessment/assets/73457195/ec2f799e-c462-4858-9345-582251537a36)

**Comment by jansenbe** [comment]
@roguetomato : the fact that no logs are created means it hangs very early on in the process, actually before even trying to start. I've seen this before when proxy server are used or with some sorts of security products (e.g. ForcePoint) that intercept traffic to localhost.

Also, before trying again ensure that all microsoft365-assessment.exe processes are killed.

**Comment by jansenbe** [comment]
@roguetomato : Issue #51 was related to an older microsoft365-assessment.exe process still running, so would recommend checking that first and sticking with version 1.8.

**Comment by roguetomato** [comment]
@jansenbe, thanks for the suggestion but the results were still the same with both versions (1.7 and 1.8) and making sure that all microsoft365-assessment.exe processes are killed before running it.

I'm still waiting for the our internal team to implement a certificate on the Azure AD application for us which could potentially help us on running the tool properly.

It could also be that we only implemented the Azure AD application on our test tenant at the moment. Does the initial assessment run on the tenant where the PowerShell is running on?

**Comment by jansenbe** [comment]
@roguetomato : you determine via the --tenant command line parameter which tenant is assessed. When you specify the use Azure AD application using --ApplicationId then that Azure AD application must be created in the Azure AD environmen that's linked to the tenant you've chosen via the --tenant parameter. See here for the generic Azure AD setup instructions: https://pnp.github.io/pnpassessment/using-the-assessment-tool/setupauth.html#creating-an-azure-ad-application-using-the-azure-ad-portal, see https://pnp.github.io/pnpassessment/addinsacs/requirements.html#permission-requirements for the specific permission requirements for the AddInACS assessment module.

**Comment by roguetomato** [comment]
@jansenbe: I was able to make it work and I've done a couple of things.

First, the certificate was successfully setup on the Azure AD application. 
So, I ran it, and it has successfully moved past the "No running Microsoft 365 Assessment found, starting one... Starting Microsoft 365 Assessment..." stage.
And you're right that it is important to kill all existing processes of the tool before running it.
However, it threw an exception at the end.

_**Error starting assessment job: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.**_

![SQLiteerror](https://github.com/pnp/pnpassessment/assets/73457195/c72ec561-810a-4c60-897f-9ea418efadd5)

Fortunately, I've seen that error on #46 and I've read there that it could be due to a security policy on my machine intercepting it.
So, I ran it on another machine, and it worked!

You can go ahead and close this ticket now. Thanks a lot for all your assistance!
