### ISSUE TITLE
Problem when running Microsoft Assessment Tool for SharePoint Add-Ins and Azure ACS deprecation

### ISSUE THREAD

**Issue by cgjeb** [pnp/pnpassessment#51]
Hi,

I've registered an azure app to use for running the process but I'm getting the error below.
"Assessment job not started due to error:"

<img width="660" alt="error_11" src="https://github.com/pnp/pnpassessment/assets/45824267/fa72b660-d85c-4ab3-9b31-3f7d670a81e9">

I made sure all relevant permissions are granted in azure following that guide.
https://pnp.github.io/pnpassessment/using-the-assessment-tool/setupauth.html

Is there anything I'm missing?

Thank you.

**Comment by jansenbe** [comment]
@cgjeb : for the AddInsACS module the minimal permission requirements are documented here: https://pnp.github.io/pnpassessment/addinsacs/requirements.html#permission-requirements. Please check if you've granted all of them.

If that's the case then please retry and provide me a copy of the generated log files at bjansen@microsoft.com

**Comment by cgjeb** [comment]
Hi @jansenbe 

I've cross-checked the permissions, and everything seems to be in place.

![image](https://github.com/pnp/pnpassessment/assets/45824267/59ea34f2-0c7a-439e-828a-a2e480163e00)

Oddly, when running, the tool does not show any logs in the folder! Could the logs be saved somewhere else?

![image](https://github.com/pnp/pnpassessment/assets/45824267/b5d8a393-a88f-436e-b78f-be3bda34f855)

![image](https://github.com/pnp/pnpassessment/assets/45824267/08808f68-ad1f-453b-a1ab-0fa7ac1034bf)

That is the sample line I'm running in the tool(I've removed our org details).
PS C:\Temp\MicrosoftAssessmentTool> .\microsoft365-assessment.exe start --mode AddInsACS --authmode application --tenant xxx.sharepoint.com --applicationid 56789xxxxxxxx --certpath "My|CurrentUser|abc"

The certificate is available in certmgr

![image](https://github.com/pnp/pnpassessment/assets/45824267/7f289ed1-e795-4252-9749-ccd5357f0a0f)

I don't know where I'm going wrong; previously, I ran the workflow assessment tool without any problems.
If you could help me capture the logs, I will then email them to you, if you don't mind.

Thank you.

**Comment by jansenbe** [comment]
@cgjeb : do you see log files in the folder hosting the .exe? Also, before retrying can you cross check that all microsoft365-assessment.exe processes are killed? If that doesn't help, then it would be great if you could pull down version 1.7 and see if that shows the same issue? Version 1.8 is the first one based upon .NET 8.0, so wondering if somehow there's an issue with that one.

**Comment by cgjeb** [comment]
@jansenbe 

Thank you for the tips.

I killed all microsoft365-assessment.exe processes, then used version 1.7 and the tool is running.

![image](https://github.com/pnp/pnpassessment/assets/45824267/7eb2a658-489a-47ac-917f-896d60e6f1e3)

**Comment by jansenbe** [comment]
@cgjeb : would it be possible to, once your run finishes, to try again with version 1.8 (first kill all assessment processes) and see if that one hangs again?

**Comment by cgjeb** [comment]
Hi @jansenbe 

I've run the tool using ver. 1.8 and it is working fine.
It looks like any running processes for needed to be killed before running a new instance. It would be nice to add it to your support articles.

![image](https://github.com/pnp/pnpassessment/assets/45824267/a4bb6813-f470-4327-8f90-01b1f304893e)


Thank you so much for all your help.

**Comment by jansenbe** [comment]
Thx, I'll update that in the docs
