### ISSUE TITLE
Unhandled exception error

### ISSUE THREAD

**Issue by Chris-1973** [pnp/pnpassessment#54]
I'm getting an Unhandled exception: when running the following command
microsoft365-assessment.exe start --mode workflow --authmode application --tenant tenantname.onmicrosoft.com --applicationid e17495d9-xxxx-xxxx-xxxxx-9c9e10af2314 --certpath "My|CurrentUser|05f1153e551e3ae9b2adxxxxxxxx93130f3e81af"

I followed the steps in the authentication page setting up an app with the correct API permissions and created a self cert that I added to the apps certificates as well as adding to my local user
https://pnp.github.io/pnpassessment/using-the-assessment-tool/setupauth.html

![image](https://github.com/pnp/pnpassessment/assets/168524437/a6be8a2a-43a0-4318-af0c-f424a72841fd)

I have tried with both v1.9 & 1.8 of the tool

**Comment by jansenbe** [comment]
@Chris-1973 : I think you're using the --tenant parameter wrong, it should be tenantname.sharepoint.com. See https://pnp.github.io/pnpassessment/workflow/assess.html#start-assessment for the details.

**Comment by Chris-1973** [comment]
Hi @jansenbe 

Yes that was the problem, working as expected now.

Thanks for the help
