### ISSUE TITLE
Assessment is sitting idle for a long time 

### ISSUE THREAD

**Issue by Oleks1976** [pnp/pnpassessment#55]
When staring assessment it gives error that assessment is not started due to graph service exception. At same time assessment is Queued and sitting idle. Any Idea how to resolve this issue
![Synex](https://github.com/pnp/pnpassessment/assets/169824551/10fcc149-838b-49ae-a56d-97d4da764a5b)

**Comment by caseyekim** [comment]
I had the same issue, manually updating the permissions to following worked for me.
![perm screenshot](https://github.com/pnp/pnpassessment/assets/59899714/e5ce5dd2-6594-4e87-b54b-5137f60a858a)

**Comment by Oleks1976** [comment]
Thank you so much for the help. It is running now. It was missing App permission

**Comment by jansenbe** [comment]
@caseyekim : thanks for helping out! 

@Oleks1976 : I'm closing the issue now.
