### ISSUE TITLE
Two instances of m365assessment.exe starting when trying to run the infopath scan

### ISSUE THREAD

**Issue by Somu76** [pnp/pnpassessment#62]
Command Used:
PS F:\AssessmentFolder> .\microsoft365-assessment.exe start --mode InfoPath --authmode application --tenant TENANTNAME.sharepoint.com --applicationid APPID --certfile ".\CERTNAME.pfx" --certpassword "CERTPASS"

OS: Windows Server 2022
Version: Latest Release (1.9.0)
I also tried Appsettings.json with a different port 25015, but that did not help... 

I am getting an error about the assessment not starting timely, and when checking the task manager, noticed that there were 2 instances being started.... what might I be doing wrong, or is there an issue with the tool?

**Comment by jansenbe** [comment]
@Somu76 : that's expected, the .exe is both a cmdline tool as a .NET Kestrel web server. Using the cmdline tool you start the web server (if not yet running) and give it the commands to execute. This approach allows for you to close the cmdline and later on come back, and auto reconnect with the running web server.

**Comment by jansenbe** [comment]
@Somu76 : I would recommend to kill both processes, then launch microsoft365-assessment.exe again. If that starts type **list** on the prompt, which should trigger the start of the web server (the second process with the same name) and connect the two. If that errors out then the common reasons are proxy servers intervening or security software (we had some issues with ForcePoint).

**Comment by jansenbe** [comment]
@Somu76 : closing per no feedback anymore, please re-open if needed
