### ISSUE TITLE
when run the sharepoint addin/acs assessment, showing  "Assessment Job not started due to error: Microsoft graph service exception"

### ISSUE THREAD

**Issue by Steven123198** [pnp/pnpassessment#63]
when run the sharepoint addin/acs assessment, showing  "Assessment Job not started due to error: Microsoft graph service exception"
you may check the screenshot of the 
<img width="863" alt="assessment tool issue" src="https://github.com/user-attachments/assets/f0be02e8-b46f-4b34-b0c1-d7e417b248ca">
<img width="767" alt="app registration API permission" src="https://github.com/user-attachments/assets/bbb18a68-efeb-4073-9005-8cfdb20434c7">

when we previous run sharepoint workflow and infopath. everything goes well. only with the issue on mode addinACS
please kindly help on this. thanks

**Comment by jansenbe** [comment]
Hi @Steven123198 , 

You are missing the Application.Read.All permissions: https://pnp.github.io/pnpassessment/addinsacs/requirements.html

![image](https://github.com/user-attachments/assets/6ba1473d-fae8-4f55-b7fd-61457301d23f)

**Comment by Steven123198** [comment]
Hi Jansenbe. thanks for your updates.  actually we already though on this in the very begining. In our tanent, we have very complex pocess for changing the API permisison for app registration.  So we used our test tenant and did the test, we found it's working well with SharepointAddin and ACS assessment. you may see the below permisison and runing results
<img width="563" alt="permission of app registration in test tenant" src="https://github.com/user-attachments/assets/08d24937-f080-4353-83cf-397db60180a1">
<img width="946" alt="test tanent workingpng" src="https://github.com/user-attachments/assets/7d04df57-5d12-454f-83f0-74bc1331cebf">
So after that we think this may caused by other issues as sharepoint workflow and infopath working well.

Hi Jansenbe. could you help and confirm if we add back Application.Read.All for Graph. then issue will not existed? 
Once you confirm, we will start our internal process for applying this permission. thanks

with best regards
Steven

**Comment by jansenbe** [comment]
Yes, you need this permissions otherwise you get the error

**Comment by Steven123198** [comment]
Hi Jansenbe. thanks for your confimation.
we are trying to elevate API permisison on this app regitration, but as our IT identity governance is scaling of external apps which access our environment. they need further more clarification from your side how Microsoft365 assessment tool works in the backed. could you provide more a bit to us so that we can apply for higher permissions? thanks.
