### ISSUE TITLE
How can we answer questions from Identity governance when applying for microsoft graph applicaiton.read.all ?

### ISSUE THREAD

**Issue by Steven123198** [pnp/pnpassessment#66]
Hi @jansenbe 

Thanks for your guidance before.
we can understand if we want to run sharepoint addin/Azure ACS assessment for the whole tanent, we need to apply for microsoft graph  **applicaiton.read.all**.

we are trying to elevate API permisison on this app regitration, but as our IT identity governance is scaling and concerning of external apps which access our environment. it can read all our application.  
How can this application be proved as safe tool when read all of our tanent application? 
Our governance need further more clarification from your side how Microsoft365 assessment tool works in the backed. could you provide more a bit to us and proved this tool to be safe so that we can apply for applicatio.read.all permissions? thanks.

**Comment by jansenbe** [comment]
The tool is open source, the latest version of the code is in this repo. There's also a dependency on the [PnP Core SDK open source library](https://github.com/pnp/pnpcore/tree/dev), feel free to verify code and share with your governance team. We need this permission as the tool needs to enumerate all legacy app principals.

**Comment by jansenbe** [comment]
Closing this issue, the assessment tool requires this permission to operate.
