### ISSUE TITLE
MacOS Version is missing 3 dependancies

### ISSUE THREAD

**Issue by nyannios** [pnp/pnpassessment#67]
The following dependancies are missing from the solution file 

PnP.Core
PnP.Core.Admin
PnP.Core.Auth

They do not appear to be included with the MacOS download from GitHub

Also, NuGet tries to download them but it fails

**Comment by jansenbe** [comment]
@nyannios : did you mark the mac file as executable as mentioned in https://pnp.github.io/pnpassessment/using-the-assessment-tool/download.html#running-on-macos-and-linux? Do know that the mac version does not have the PowerBI report generation capability, if you need that you anyhow have to use the Windows version, if you're ok with the CSV files that you're good.

I personally don't have a mac device, but I'll see what I can do

**Comment by jansenbe** [comment]
@nyannios : I think I misunderstood your question...are you trying to build the solution yourselves? If so, then you indeed need to pull down PnP Core SDK (https://github.com/pnp/pnpcore/tree/dev) under the same root folder where you pulled in the assessment tool. If you open the solution, then it will pick up dependencies. Alternatively, you can update the solution/project files and directly use the nuget packages for those dependencies

**Comment by jansenbe** [comment]
Closing per no feedback
